packages:
  - "packages/*"
  - "deployers/*"
  - "stores/*"
  - "speech/*"
  - "voice/*"
  - "workflows/*"
  - "client-sdks/*"
  - "!packages/cli/admin"
  - "integrations/*"
  - "examples/dane"
  - "examples/experimental-auth-weather-agent"
  - "packages/cli/src/playground"
  - "packages/*/integration-tests"
  - "packages/cloud"