# test-core-unprivileged.yml
name: Core Package Tests (Unprivileged)

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/core/**'
      - '.github/workflows/test-core.yml'
      - '.github/workflows/test-core-privileged.yml'

jobs:
  test:
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build cli
        run: pnpm build:core
